### PR TITLE
Add python 3.12 support

### LINKED ISSUE #49: datetime.utcnow and datetime.utcfromtimestamp are deprecated in Python 3.12
> datetime.datetime’s utcnow() and utcfromtimestamp() are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call now() and fromtimestamp() with the tz parameter set to datetime.UTC. (Contributed by Paul Ganssle in python/cpython#103857.)

```
croniter/src/croniter/tests/test_croniter.py
960:            dt = datetime.utcfromtimestamp(c.get_next())
980:            dt = datetime.utcfromtimestamp(c.get_next())
1003:            dt = datetime.utcfromtimestamp(c.get_next())

croniter/src/croniter/croniter.py
230:        result = datetime.datetime.utcfromtimestamp(timestamp)
862:        start, stop = (datetime.datetime.utcfromtimestamp(t) for t in (start, stop))
```

### PR DESCRIPTION
**Pull request by rafsaf**
Added python 3.12 around the project.

This will also fix https://github.com/kiorky/croniter/issues/49 with migration from utcfromtimestamp to fromtimestamp in backward compatible manner (hopefully). 
I was able to run tests with tox with py2.7 after above change, but had problems on ancient <=3.5, but this should be also ok.

Original deprecation warnings visible in tests include expected fix (discussion here https://discuss.python.org/t/deprecating-utcnow-and-utcfromtimestamp/26221):
```
src/croniter/tests/test_croniter.py: 1563 warnings
src/croniter/tests/test_croniter_hash.py: 138 warnings
src/croniter/tests/test_croniter_random.py: 18 warnings
src/croniter/tests/test_croniter_range.py: 2769 warnings
  /home/rafsaf/projects/croniter/src/croniter/croniter.py:230: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    result = datetime.datetime.utcfromtimestamp(timestamp)

src/croniter/tests/test_croniter.py: 10 warnings
  /home/rafsaf/projects/croniter/src/croniter/tests/test_croniter.py:1003: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    dt = datetime.utcfromtimestamp(c.get_next())

src/croniter/tests/test_croniter.py: 10 warnings
  /home/rafsaf/projects/croniter/src/croniter/tests/test_croniter.py:960: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    dt = datetime.utcfromtimestamp(c.get_next())

src/croniter/tests/test_croniter.py: 10 warnings
  /home/rafsaf/projects/croniter/src/croniter/tests/test_croniter.py:980: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    dt = datetime.utcfromtimestamp(c.get_next())

src/croniter/tests/test_croniter_range.py::CroniterRangeTest::test_auto_ret_type
src/croniter/tests/test_croniter_range.py::CroniterRangeTest::test_auto_ret_type
  /home/rafsaf/projects/croniter/src/croniter/croniter.py:862: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    start, stop = (datetime.datetime.utcfromtimestamp(t) for t in (start, stop))
```

### CODE REVIEW

**Comment by kiorky** [comment]
Thx !
I gonna merge/release this.

**Comment by kiorky** [comment]
Looking better in the PR content, it breaks python2 support (and tests).
It's not mergeable as it is.
I may drop py2 not before 2027.

**Comment by kiorky** [comment]
this is the failing test

```
================================================================================================================= FAILURES =================================================================================================================
________________________________________________________________________________________________________ CroniterTest.test_dst_iter ________________________________________________________________________________________________________

self = <croniter.tests.test_croniter.CroniterTest testMethod=test_dst_iter>

    def test_dst_iter(self):
        tz = pytz.timezone('Asia/Hebron')
        now = datetime(2022, 3, 26, 0, 0, 0, tzinfo=tz)
        it = croniter('0 0 * * *', now)
        ret = [
            it.get_next(datetime).isoformat(),
            it.get_next(datetime).isoformat(),
            it.get_next(datetime).isoformat(),
        ]
        self.assertEqual(ret, [
            '2022-03-26T00:00:00+02:00',
            '2022-03-27T01:00:00+03:00',
>           '2022-03-28T00:00:00+03:00'])
E       AssertionError: Lists differ: ['2022-03-26T01:00:00+03:00', ... != ['2022-03-26T00:00:00+02:00', ...
E       
E       First differing element 0:
E       '2022-03-26T01:00:00+03:00'
E       '2022-03-26T00:00:00+02:00'
E       
E       - ['2022-03-26T01:00:00+03:00',
E       ?               ^        ^
E       
E       + ['2022-03-26T00:00:00+02:00',
E       ?               ^        ^
E       
E       -  '2022-03-26T23:00:00+03:00',
E       ?            ^ ^^
E       
E       +  '2022-03-27T01:00:00+03:00',
E       ?            ^ ^^
E       
E       -  '2022-03-27T00:00:00+03:00']
E       ?            ^
E       
E       +  '2022-03-28T00:00:00+03:00']
E       ?            ^

src/croniter/tests/test_croniter.py:1143: AssertionError
```

**Comment by rafsaf** [comment]
Thank you for the fast reply and running tests!

Interesting, I'm not sure how I missed that failing test :( but will look into it and maybe there is some simple solution, in about a year from now (that is 2024 which is before 2027) `utcfromtimestamp` will be gone

(Well custom function utcfromtimestamp that has a different body depending on python 2 or python 3 probably is the way to go)

**Comment by kiorky** [comment]
Uhm, as i saw you also did test on py2, i made a new py venv, and tested from there. 
Seems there was i think something old/odd in my previous venv, tests are passing there...

Bissecting dependencies was not hard, it's because of pytz which must be `>2021.1`.

That requirement breaks backward compatibility:
- old installs will need to take care of also upgrading pytz
- pytz is now an hard requirement (it was optionnal before)


I will so make a major release as it is not a big dependency to add, but also it will with not much extra cost help to maintain both 2, and 3 compat.

**Comment by kiorky** [comment]
2.0.0 is out, thanks for your contribution.

**Pull request merged**
