### PR TITLE
All black changes (meta PR do not merge)

### PR DESCRIPTION
**Pull request by evanpurkhiser**
**DO NOT MERGE**

This is an integration PR just to show that all test pass with what the final integration looks like.

I wasn't able to open every PR as a commit, but @kiorky when you're back online, if thee individual commits look good to you feel free to pull them into master

221b90225d55c5c60b9a5c459c54971e533064cb → https://github.com/kiorky/croniter/pull/128 
f5d6c6ff13c4dc840f05a4a0b1b1c43f8f7f0f84 → https://github.com/kiorky/croniter/pull/131 
3f1a5f359bd6f8dfd712f21c67608ac878512e72 → https://github.com/kiorky/croniter/pull/130 
6945be464cfdd42776b00a7d61dc0cb5a7dd1dd5 → https://github.com/kiorky/croniter/pull/129
dd1311a413d7c0ff70a0c94f24ea293f4d164a2b → https://github.com/kiorky/croniter/pull/132
cd5f2b4c1a4ee85444292e2b09b8bdb039df5031 → [no PR yet, feel free to pull in]
e62d33007be9db106cf92cd10cb5d5f7b9cee61a → [no PR yet, feel free to pull in]
58bdc7ac77793842abd57d833fea73c9ccd74fa8 → [no PR yet, feel free to pull in]
f7c932020529b58da81696ad311733c88460aa74 → [no PR yet, feel free to pull in]
6bd5f88c02a3330b3bc0fd5df825e3fa1930f1c6 → [no PR yet, feel free to pull in]
97bd84449b0f712d1b94ca120603cdb275557553 → https://github.com/kiorky/croniter/pull/123

Part of #99

### CODE REVIEW

**Comment by kiorky** [comment]
i cherrypicked / rebased all the commits except the black one as we wil merge it at the end.

**Comment by kiorky** [comment]
everything is merged in, even the black setup.

**Comment by evanpurkhiser** [comment]
Woohoo!!! thanks for getting this all merged!

**Comment by evanpurkhiser** [comment]
Probably overkill but this really does make it a lot easier to contribute! :)

**Pull request closed without merging**
