### PR TITLE
Drop support for old Pythons; modernize & repair CI

### PR DESCRIPTION
**Pull request by akx**
* The main change in this PR is to change the Python support level for the library to Python 3.8 and newer only. (Python 3.8, too, has been end-of-life for 2 weeks now, but it's still widely used, and readily available on GitHub Actions.)
  * It turns out that some of the test suite has been failing on Python 2 for a while now, but since it hasn't been in CI, no one knew. Presumably no one cares about Python 2 support for new versions of the library, either.
  * Python 3.6 and 3.7 will _probably_ work, but Tox 4 doesn't support them, and Python 3.6 doesn't exist on GitHub Actions. `python_requires` could thus be `'>=3.6'`, but we'd likely not know if it breaks.
* Secondly, it modernizes the Tox configuration that's used by the CI pipeline to use Tox 4, a split lint task (no need to lint on all versions...), and `tox-gh` for GitHub Python version determination.
* Finally, it fixes coverage reporting to happen again (via `pytest-cov`).

Since this changes the supported Python versions, I think this would be a semver-major change. I'm not sure if `croniter` is semver versioned.

Please see https://github.com/akx/croniter/pull/1 for the CI passing :)

### CODE REVIEW

**Comment by kiorky** [comment]
not ok for dropping support, we  still support from python 2.6

**Comment by akx** [comment]
> we still support from python 2.6

Yes, so far. As I said, this would be a semver-major version bump. Is there a reason to support Python 2.x going forward? [Python 2.6 has been EOL for 10 years, Python 2.7 has been EOL for 4 years. ](https://endoflife.date/python)

I can of course change this PR to not change the version requirements. However, looks like this package hasn't been [CI tested on Python 2.7 since April 2023](https://github.com/kiorky/croniter/commit/4af0bd8e845e5981cba70347fab25049f8b15f2a) and [Python 2.6 since February 2020](https://github.com/kiorky/croniter/commit/7d360056a2663364e21488e2ad64306b9465b540), so unless someone is manually testing on those versions of Python, there's really no guarantees. (As it is, testing locally on Python 2.7.18, there are 6 failing tests. I have no easy way of installing Python 2.6 on my machine.)

**Comment by kiorky** [comment]
Yes i know some project still use it from py2.

**Comment by akx** [comment]
> Yes i know some project still use it from py2.

Okay. But those projects won't break if versions 4.0+ of croniter only support still-supported versions of Python.

In any case, see #94 for a PR that makes the current version's tests actually pass on Python 2.7 again.

**Comment by akx** [comment]
So @kiorky, should I just close this PR?

**Comment by kiorky** [comment]
I'm already taking bits of this PR to merge them by myself, a lot of thanks for all the ideas, though.
I cant take it as is as i want  to merge along things i had to do to modernize  other things due for a long time, and this to be overall coherent.
Look in the following days (i hope today, but not sure will have time to finish it :).
If you still see some minor points that you want in, you can then rebase this PR, that's why i didn't closed it 

In all cases, i'll poke you when done.

And again, really, thanks for the ideas and you will be quoted in next changelog as-is :) !

**Comment by kiorky** [comment]
- 3.0.4 is released with #97, quoting you as a major contributor of this release
- i manually merged everything i found cool in your PR.
- I 'm not willing to use tox-gh, so do no waste your time refreshing this PR with it.

Feel free to rebase / add something else you would find interresting.

Thanks !

**Pull request closed without merging**
